"""changed field names in loan table

Revision ID: 53a72effe65b
Revises: 38aefe72d3b2
Create Date: 2025-10-24 14:41:10.573810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53a72effe65b'
down_revision = '38aefe72d3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('return_date', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_loans_returned_at'))
        batch_op.create_index(batch_op.f('ix_loans_return_date'), ['return_date'], unique=False)
        batch_op.drop_column('due_at')
        batch_op.drop_column('returned_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_loans_return_date'))
        batch_op.create_index(batch_op.f('ix_loans_returned_at'), ['returned_at'], unique=False)
        batch_op.drop_column('return_date')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
